FROM golang:1.16
WORKDIR /app
COPY go.mod go.sum ./
RUN go mod download
COPY . .
RUN CGO_ENABLED=0 GOOS=linux go build -a -installsuffix cgo -o docker_go_mux_production .

FROM alpine:latest
RUN apk --no-cache add ca-certificates
WORKDIR /root/
COPY --from=0 /app .

EXPOSE 3000

COPY scripts/*.sh /scripts/
RUN chmod a+x /scripts/*.sh
