# docker-compose.yml
version: "3.0"
services:
  db:
    image: postgres:9.6
    container_name: postgres9
    environment:
      POSTGRES_PASSWORD: password
    volumes:
      - db_data:/var/lib/postgresql/data
      - ./scripts/init.sql:/docker-entrypoint-initdb.d/init.sql
    restart: always
  web:
    build:
      context: .
      dockerfile: ./docker/app/Dockerfile.prod
    volumes:
      - app:/app
    environment:
      DB_HOST: db
      DB_PORT: 5432
      DB_USER: postgres
      DB_PASS: password
      DB_NAME: docker_go_mux
      PORT: 3000
      GO_ENV: production
    ports:
      - "3000:3000"
    depends_on:
      - db
    command: sh /scripts/prod.sh
    restart: always
  nginx:
    build:
      context: .
      dockerfile: ./docker/nginx/Dockerfile
      args:
        - HOST=localhost
    restart: always
    depends_on:
      - web
    ports:
      - 80:80
      - 443:443
volumes:
  app:
  db_data:
